# Generated by Django 6.0.2 on 2026-04-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainer_Specialization', to='Gym.specialization'),
        ),
    ]
