# Generated by Django 6.0.4 on 2026-04-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_alter_trainer_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AlterModelOptions(
            name='gymclass',
            options={'verbose_name_plural': 'Gym Classes'},
        ),
        migrations.AddField(
            model_name='gymclass',
            name='members',
            field=models.ManyToManyField(related_name='GymClass_Member', to='Gym.member'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='start_date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymclass',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GymClass_Trainer', to='Gym.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_damaged', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipment_Branch', to='Gym.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
