# Generated by Django 6.0.4 on 2026-04-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_branch_alter_gymclass_options_gymclass_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymclass',
            name='title',
        ),
    ]
