# Generated by Django 6.0.4 on 2026-04-16 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_remove_gymclass_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GymClass_Specializatio', to='Gym.specialization'),
        ),
    ]
