# Generated by Django 6.0.4 on 2026-04-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0005_gymclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GymClass_Specializatio', to='Gym.specialization'),
            preserve_default=False,
        ),
    ]
