# Generated by Django 6.0.4 on 2026-04-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0006_alter_gymclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GymClass_Specializatio', to='Gym.specialization'),
        ),
    ]
