# Generated by Django 6.0.4 on 2026-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0007_alter_gymclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
